[project]
name = "deepflow-client"
version = "0.9.0"
dependencies = [
    "requests==2.32.3",
    "prettytable==3.14.0"
]

[tool.setuptools.packages.find]
include = ["dpanda*"]

[project.scripts]
deepflow = "deepflow.cli:cli"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
